name: Download and Update Files

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday 

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download rules
      run: |
        curl -L -o "./rules/ir.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
        curl -L -o "./rules/ads.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ads.txt"
        curl -L -o "./rules/malware.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
        curl -L -o "./rules/phishing.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt"
        curl -L -o "./rules/cryptominers.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt"
        curl -L -o "./rules/apps.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/apps.txt"
        curl -L -o "./rules/ircidr.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
        curl -L -o "./rules/private.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/private.txt"
        curl -L -o "./rules/irasn.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.txt"
        curl -L -o "./rules/category-ads-all.txt" "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M ') 🌿"
        git push --force
